# Generated by Django 3.2.7 on 2022-12-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pic',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
