# Generated by Django 4.0.2 on 2022-02-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_name_topic_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='names',
            new_name='name',
        ),
    ]
