# Generated by Django 3.2.7 on 2022-12-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pic',
            field=models.ImageField(default='lost-items.svg', null=True, upload_to=''),
        ),
    ]
