# Generated by Django 3.2.12 on 2022-03-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
