# Generated by Django 3.2.12 on 2022-03-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_room_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='complete',
        ),
        migrations.AddField(
            model_name='message',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
